[project]
name = "solar-simulator"
description = "Software for the PSAS Solar Simulator used for testing OreSat."
version = "0.1.0"
requires-python = ">=3.14"
license = { text = "GPL-3.0" }
dependencies = [
    "adafruit-circuitpython-ads1x15",
    "adafruit-circuitpython-mcp4728",
]

[project.optional-dependencies]
dev = [
    "circuitpython-build-tools",
    "pytest",
    "pytest-cov",
    "pytest-mock",
    "ruff",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = "src/solar_simulator/lib"

[tool.ruff]
line-length = 100

[tool.ruff.format]
quote-style = "preserve"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    # See https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules
    "Q000",     # bad-quotes-inline-string
    "Q002",     # bad-quotes-docstring
    "D300",     # triple-single-quotes
    "COM812",   # prohibited-trailing-comma
    "ISC001",   # single-line-implicit-string-concatenation
    "D102",     # undocumented-public-method
    "D105",     # undocumented-magic-method
    "D203",     # one-blank-line-before-class
    "D213",     # multi-line-summary-second-line
    "FIX",      # flake8-fixme
    "TD001",    # invalid-todo-tag
    "TD002",    # missing-todo-author
    "TD003",    # missing-todo-link
    "TD004",    # missing-todo-colon
    "EM101",    # raw-string-in-exception
    "EM102",    # f-string-in-exception
    "D413",     # blank-line-after-last-section
    "TRY003",   # raise-vanilla-args
    "PLR2004",  # magic value used in comparison
    "PLR0911",  # too many return statements
    "CPY001",
    "TC001",
    "T201",
]

[tool.ruff.lint.per-file-ignores]
# Test-specific lint ignores.
"tests/**/test_*.py" = [
    "S101",     # assert - pytest prefers plain assert
    "PLC0415",  # import - pytests need flexibility around when to import
    "D100",     # modules
    "D101",     # classes
    "D102",     # methods
    "D103",     # functions
    "D104",     # package
    "D105",     # magic methods
    "D106",     # nested classes
    "D107",     # __init__
]